min_dpi = 80
max_dpi = 320
dpi = 160
wireless = false
resolution = 480
fps = 30
transition_mode = 2
aa_video_transition_mode = 0
transition_speed = 2.399759531021118
aa_video_transition_speed = 1.4874999523162842
theme = 0
gfx_model = 0
